# Generated by Django 4.0.3 on 2022-03-24 15:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_group_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouptraining',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='training',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='grouptraining',
            name='time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='training',
            name='time',
            field=models.TimeField(),
        ),
    ]
